site_name: INFN CMS Analysis Facility
theme:
  name: material
  palette:
    primary: "Deep Blue"
    accent: "Light Blue"
  logo: logo.jpeg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
nav:
  - Introduction: "introduction.md"
  - How it works:
      - Architecture and Components: "how_it_works/components.md"
      #- Network: "WIP.md"
      #- Data access: "WIP.md"
      #- Security: "WIP.md"
      #- Resources: "how_it_works/available_resources.md"
  - Quick Start:
      - Requirements: "tutorials/reqs.md"
      - For users:
          - Using Dask:
              - Initialization: "tutorials/dask_init.md"
              - Cluster management: "tutorials/dask_management.md"
              - Interactive analysis: "tutorials/dask_interactive.md"
              - Python script: "tutorials/dask_scripting.md"
          - Using HTCondor:
              - Setting up the environment: "tutorials/htc_init.md"
              - Submit your first job: "tutorials/htc_job.md"
          - Data:
              - AAA Access: "tutorials/aaa_access.md"
          - Issues: "tutorials/issues.md"
  - DevOps guide:
      - General info: "dev/dev.md"
      #- Adding new users:
      #    - IAM: "dev/iam.md"
      #    - HTCondor: "dev/htc.md"
  - FAQs: "faqs.md"
repo_name: "comp-dev-cms-ita/AnalysisFacility"
repo_url: "https://github.com/comp-dev-cms-ita/AnalysisFacility.git"

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/comp-dev-cms-ita"

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
